// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectosena.Context;

#nullable disable

namespace proyectosena.Migrations
{
    [DbContext(typeof(RecyRouteDbContext))]
    [Migration("20260801195047_CreateHistoryTable")]
    partial class CreateHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyectosena.Models.CollectionManagement", b =>
                {
                    b.Property<Guid>("IdManagement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdManager")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRequest")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ManagerObservations")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("StatusChangeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdManagement");

                    b.HasIndex("IdManager");

                    b.HasIndex("IdRequest");

                    b.ToTable("CollectionManagement", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.CollectionRequest", b =>
                {
                    b.Property<Guid>("IdRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CitizenObservations")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CollectionAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollectionTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("WasteTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdRequest");

                    b.HasIndex("IdUser");

                    b.ToTable("CollectionRequest", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.DocumentType", b =>
                {
                    b.Property<Guid>("IdDocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdDocumentType");

                    b.ToTable("DocumentType", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.History", b =>
                {
                    b.Property<Guid>("IdHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("IdRequest")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdHistory");

                    b.HasIndex("IdRequest");

                    b.HasIndex("IdUser");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.Role", b =>
                {
                    b.Property<Guid>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRole");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdDocumentType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_Email");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdDocumentType", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_Document");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.CollectionManagement", b =>
                {
                    b.HasOne("proyectosena.Models.User", "Manager")
                        .WithMany("CollectionManagement")
                        .HasForeignKey("IdManager")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CollectionManagement_User");

                    b.HasOne("proyectosena.Models.CollectionRequest", "CollectionRequest")
                        .WithMany("CollectionManagement")
                        .HasForeignKey("IdRequest")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CollectionManagement_CollectionRequest");

                    b.Navigation("CollectionRequest");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("proyectosena.Models.CollectionRequest", b =>
                {
                    b.HasOne("proyectosena.Models.User", "User")
                        .WithMany("CollectionRequests")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CollectionRequest_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.History", b =>
                {
                    b.HasOne("proyectosena.Models.CollectionRequest", "CollectionRequest")
                        .WithMany("History")
                        .HasForeignKey("IdRequest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_History_CollectionRequest");

                    b.HasOne("proyectosena.Models.User", "User")
                        .WithMany("History")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_History_User");

                    b.Navigation("CollectionRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.User", b =>
                {
                    b.HasOne("proyectosena.Models.DocumentType", "DocumentType")
                        .WithMany("User")
                        .HasForeignKey("IdDocumentType")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_DocType");

                    b.HasOne("proyectosena.Models.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("DocumentType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("proyectosena.Models.CollectionRequest", b =>
                {
                    b.Navigation("CollectionManagement");

                    b.Navigation("History");
                });

            modelBuilder.Entity("proyectosena.Models.DocumentType", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.User", b =>
                {
                    b.Navigation("CollectionManagement");

                    b.Navigation("CollectionRequests");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
