// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyectosena.Context;

#nullable disable

namespace proyectosena.Migrations
{
    [DbContext(typeof(RecyRouteDbContext))]
    partial class RecyRouteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proyectosena.Models.ChatHistory", b =>
                {
                    b.Property<Guid>("IdChatHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("IdRequest")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSender")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("SendDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("IdChatHistory");

                    b.HasIndex("IdRequest");

                    b.HasIndex("IdSender");

                    b.ToTable("ChatHistory", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.CollectionManagement", b =>
                {
                    b.Property<Guid>("IdManagement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdManager")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdRequest")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagerObservations")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("StatusChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdManagement");

                    b.HasIndex("IdManager");

                    b.HasIndex("IdRequest");

                    b.ToTable("CollectionManagement", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.CollectionRequest", b =>
                {
                    b.Property<Guid>("IdRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CitizenObservations")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CollectionAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CollectionTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("WasteTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdRequest");

                    b.HasIndex("IdUser");

                    b.ToTable("CollectionRequest", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.DocumentType", b =>
                {
                    b.Property<Guid>("IdDocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("IdDocumentType");

                    b.ToTable("DocumentType", (string)null);

                    b.HasData(
                        new
                        {
                            IdDocumentType = new Guid("63d5f1a7-6c0c-4a05-adf8-d65964d2b3b1"),
                            Abbreviation = "CC",
                            DocumentName = "Cédula de ciudadanía"
                        },
                        new
                        {
                            IdDocumentType = new Guid("fcccb874-75f3-4374-b8e5-a7a92b084d6c"),
                            Abbreviation = "PA",
                            DocumentName = "Pasaporte"
                        },
                        new
                        {
                            IdDocumentType = new Guid("5bcb367c-1f41-4c5a-b120-f01f35159dd8"),
                            Abbreviation = "CE",
                            DocumentName = "Cédula de extranjería"
                        });
                });

            modelBuilder.Entity("proyectosena.Models.History", b =>
                {
                    b.Property<Guid>("IdHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("IdRequest")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdHistory");

                    b.HasIndex("IdRequest");

                    b.HasIndex("IdUser");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.ManagerApplication", b =>
                {
                    b.Property<Guid>("IdApplication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("IdReviewer")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("IdApplication");

                    b.HasIndex("IdReviewer");

                    b.HasIndex("IdUser", "Status")
                        .HasDatabaseName("IX_ManagerApplication_User_Status");

                    b.ToTable("ManagerApplication", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.Notification", b =>
                {
                    b.Property<Guid>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("IdRequest")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdRequest");

                    b.HasIndex("IdUser");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.Role", b =>
                {
                    b.Property<Guid>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRole");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            IdRole = new Guid("00000000-0000-0000-0000-000000000001"),
                            RoleDescription = "User with full access to the system.",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            IdRole = new Guid("00000000-0000-0000-0000-000000000002"),
                            RoleDescription = "User responsible for managing collection requests.",
                            RoleName = "Manager"
                        },
                        new
                        {
                            IdRole = new Guid("7d759012-4d17-46e8-bce8-d74fdf171eab"),
                            RoleDescription = "User who can submit collection requests.",
                            RoleName = "Citizen"
                        });
                });

            modelBuilder.Entity("proyectosena.Models.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("IdDocumentType")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_Email");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdDocumentType", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_Document");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("proyectosena.Models.ChatHistory", b =>
                {
                    b.HasOne("proyectosena.Models.CollectionRequest", "CollectionRequest")
                        .WithMany("ChatHistory")
                        .HasForeignKey("IdRequest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChatHistory_CollectionRequest");

                    b.HasOne("proyectosena.Models.User", "Sender")
                        .WithMany("ChatHistory")
                        .HasForeignKey("IdSender")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ChatHistory_User");

                    b.Navigation("CollectionRequest");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("proyectosena.Models.CollectionManagement", b =>
                {
                    b.HasOne("proyectosena.Models.User", "Manager")
                        .WithMany("CollectionManagement")
                        .HasForeignKey("IdManager")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CollectionManagement_User");

                    b.HasOne("proyectosena.Models.CollectionRequest", "CollectionRequest")
                        .WithMany("CollectionManagement")
                        .HasForeignKey("IdRequest")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CollectionManagement_CollectionRequest");

                    b.Navigation("CollectionRequest");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("proyectosena.Models.CollectionRequest", b =>
                {
                    b.HasOne("proyectosena.Models.User", "User")
                        .WithMany("CollectionRequests")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CollectionRequest_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.History", b =>
                {
                    b.HasOne("proyectosena.Models.CollectionRequest", "CollectionRequest")
                        .WithMany("History")
                        .HasForeignKey("IdRequest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_History_CollectionRequest");

                    b.HasOne("proyectosena.Models.User", "User")
                        .WithMany("History")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_History_User");

                    b.Navigation("CollectionRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.ManagerApplication", b =>
                {
                    b.HasOne("proyectosena.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("IdReviewer")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ManagerApplication_Reviewer");

                    b.HasOne("proyectosena.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ManagerApplication_User");

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.Notification", b =>
                {
                    b.HasOne("proyectosena.Models.CollectionRequest", "CollectionRequest")
                        .WithMany("Notification")
                        .HasForeignKey("IdRequest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Notification_CollectionRequest");

                    b.HasOne("proyectosena.Models.User", "User")
                        .WithMany("Notification")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("CollectionRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.User", b =>
                {
                    b.HasOne("proyectosena.Models.DocumentType", "DocumentType")
                        .WithMany("User")
                        .HasForeignKey("IdDocumentType")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_DocType");

                    b.HasOne("proyectosena.Models.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("DocumentType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("proyectosena.Models.CollectionRequest", b =>
                {
                    b.Navigation("ChatHistory");

                    b.Navigation("CollectionManagement");

                    b.Navigation("History");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("proyectosena.Models.DocumentType", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("proyectosena.Models.User", b =>
                {
                    b.Navigation("ChatHistory");

                    b.Navigation("CollectionManagement");

                    b.Navigation("CollectionRequests");

                    b.Navigation("History");

                    b.Navigation("Notification");
                });
#pragma warning restore 612, 618
        }
    }
}
